import {
  Plane,
  Building2,
  Calendar,
  Armchair,
  DollarSign,
  Tag,
  Users,
  BarChart3,
  TrendingUp,
  PieChart,
  FileText,
  Settings,
  ChevronDown,
  ChevronRight,
  Home,
  Plus,
  Search,
  Edit,
  Trash2,
  Eye,
  Target,
  CreditCard,
  Gift,
  UserCheck,
  Clock,
  MapPin,
  Menu,
  X,
} from "lucide-react";

export const sidebarSections = [
  {
    id: "overview",
    title: "Dashboard",
    icon: Home,
    color: "from-primary to-[#6F1E51]",
    items: [
      { id: "overview", label: "Overview", icon: BarChart3, count: null },
    ],
  },
  {
    id: "airlines",
    title: "Airline Management",
    icon: Building2,
    color: "from-indigo-500 to-indigo-600",
    items: [
      {
        id: "airlines-list",
        label: "All Airlines",
        icon: Building2,
        count: 12,
      },
      {
        id: "airlines-create",
        label: "Create Airline",
        icon: Plus,
        count: null,
      },
      {
        id: "airlines-profile",
        label: "Airline Profile",
        icon: UserCheck,
        count: null,
      },
      {
        id: "airlines-settings",
        label: "Settings",
        icon: Settings,
        count: null,
      },
    ],
  },
  {
    id: "flights",
    title: "Flight Management",
    icon: Plane,
    color: "from-[#B53471] to-[#82589F]",
    items: [
      { id: "flights-list", label: "All Flights", icon: Plane, count: 45 },
      { id: "flights-create", label: "Create Flight", icon: Plus, count: null },
      {
        id: "flights-schedule",
        label: "Flight Schedule",
        icon: Calendar,
        count: null,
      },
      {
        id: "flights-routes",
        label: "Route Management",
        icon: MapPin,
        count: 8,
      },
      { id: "flights-status", label: "Flight Status", icon: Clock, count: 3 },
    ],
  },
  {
    id: "seats",
    title: "Seat Management",
    icon: Armchair,
    color: "from-purple-500 to-purple-600",
    items: [
      { id: "seats-map", label: "Seat Maps", icon: Armchair, count: 45 },
      {
        id: "seats-config",
        label: "Seat Configuration",
        icon: Settings,
        count: null,
      },
      {
        id: "seats-classes",
        label: "Class Management",
        icon: Target,
        count: 3,
      },
      {
        id: "seats-availability",
        label: "Availability",
        icon: Eye,
        count: null,
      },
    ],
  },
  {
    id: "pricing",
    title: "Pricing & Discounts",
    icon: DollarSign,
    color: "from-green-500 to-emerald-500",
    items: [
      {
        id: "pricing-base",
        label: "Base Pricing",
        icon: DollarSign,
        count: null,
      },
      {
        id: "pricing-dynamic",
        label: "Dynamic Pricing",
        icon: TrendingUp,
        count: null,
      },
      { id: "discounts-list", label: "Discount Codes", icon: Tag, count: 8 },
      {
        id: "discounts-create",
        label: "Create Discount",
        icon: Gift,
        count: null,
      },
      {
        id: "pricing-rules",
        label: "Pricing Rules",
        icon: FileText,
        count: 12,
      },
    ],
  },
  {
    id: "bookings",
    title: "Bookings",
    icon: Users,
    color: "from-orange-500 to-red-500",
    items: [
      { id: "bookings-list", label: "All Bookings", icon: Users, count: 234 },
      {
        id: "bookings-pending",
        label: "Pending Bookings",
        icon: Clock,
        count: 12,
      },
      {
        id: "bookings-confirmed",
        label: "Confirmed",
        icon: UserCheck,
        count: 198,
      },
      { id: "bookings-cancelled", label: "Cancelled", icon: X, count: 24 },
      {
        id: "bookings-payments",
        label: "Payment Status",
        icon: CreditCard,
        count: 5,
      },
    ],
  },
  {
    id: "reports",
    title: "Reports & Analytics",
    icon: BarChart3,
    color: "from-pink-500 to-rose-500",
    items: [
      {
        id: "reports-sales",
        label: "Sales Reports",
        icon: TrendingUp,
        count: null,
      },
      {
        id: "reports-occupancy",
        label: "Seat Occupancy",
        icon: PieChart,
        count: null,
      },
      {
        id: "reports-revenue",
        label: "Revenue Analysis",
        icon: DollarSign,
        count: null,
      },
      {
        id: "reports-performance",
        label: "Performance",
        icon: BarChart3,
        count: null,
      },
      {
        id: "reports-custom",
        label: "Custom Reports",
        icon: FileText,
        count: 3,
      },
    ],
  },
];
